name: First python workflow
on: workflow_dispatch

jobs:
 install-python:
  runs-on: ubuntu-latest

  steps:
   - name: checkout code
     uses: actions/checkout@v4

   - name: set up python 3.10
     uses: actions/setup-python@v5.6.0
     with:
      python-version: '3.10'
   - name: Display python
     run: python --version
      
